# include C:\Users\JIN\Documents\GitHub\HealthIndex\source\quad.run;
reset;
model C:\Users\JIN\Documents\GitHub\HealthIndex\source\quad.mod;
data C:\Users\JIN\Documents\GitHub\HealthIndex\source\pars.dat;
data C:\Users\JIN\Documents\GitHub\HealthIndex\source\Ematrix.dat;
option solver cplex;
solve;
display w;
printf {k in 1..n_w} "%12.6e\n", w[k] > C:\Users\JIN\Documents\GitHub\HealthIndex\data\tmp\w.res;